---
title: "Omop_training_A2"
author: "Danielle N"
date: '2022-05-04'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Install packages

```{r install_packages,  message=FALSE, warning=FALSE,echo=FALSE}

rm(list = ls()) # clear environment

library(here)
library(readr)
library(DBI)
library(RSQLite)
library(dplyr)
library(stringr)
library(DT)
library(kableExtra)
library(CodelistGenerator)
library(Eunomia)
library(dbplyr)
library(tictoc)
library(ggplot2)
library(compareGroups)
library(table1)
library(RPostgreSQL)

```

## Upload data

Using the Eunomia dataset from OHDSI (https://github.com/OHDSI/Eunomia)
```{r download_eunomia,  message=FALSE, warning=FALSE,echo=FALSE}

#upload Eunomia
untar(xzfile(system.file("sqlite", "cdm.tar.xz", package = "Eunomia"), open = "rb"), exdir =  tempdir())

db <- DBI::dbConnect(RSQLite::SQLite(), paste0(tempdir(),"\\cdm.sqlite"))

#check version
#get_vocab_version(db=db, vocabulary_database_schema = "main")


# for other databases

# server     <- Sys.getenv("DB_SERVER_xxx")
# server_dbi <- Sys.getenv("DB_SERVER_xxx")
# user       <- Sys.getenv("DB_USER")
# password   <- Sys.getenv("DB_PASSWORD")
# port       <- Sys.getenv("DB_PORT") 
# host       <- Sys.getenv("DB_HOST") 
# 
# db <- dbConnect(RPostgreSQL::PostgreSQL(),
#                 dbname = server_dbi,
#                 port = port,
#                 host = host, 
#                 user = user, 
#                 password = password)


```

## Defining a cohort
We want to create a cohort of everyone with a prescription for ... whichever drug has the most prevalence in the dataset (aspirin)

```{r, eval=TRUE}

#Set up the basics
targetDialect              <- "postgresql" 
cdm_database_schema        <- "main" # this might be different for other databases
vocabulary_database_schema <- "main" # this might be different for other databases
results_database_schema    <- "results"

#create links to all the database tables
person_db <- tbl(db, sql(paste0("SELECT * FROM ",cdm_database_schema,".person")))
observation_period_db <- tbl(db, sql(paste0("SELECT * FROM ",cdm_database_schema,".observation_period")))
visit_occurrence_db <- tbl(db, sql(paste0("SELECT * FROM ",cdm_database_schema,".visit_occurrence")))
condition_occurrence_db <- tbl(db, sql(paste0("SELECT * FROM ",cdm_database_schema,".condition_occurrence")))
measurement_db <- tbl(db, sql(paste0("SELECT * FROM ",cdm_database_schema,".measurement")))
observation_db <- tbl(db, sql(paste0("SELECT * FROM ",cdm_database_schema,".observation")))
drug_era_db <- tbl(db, sql(paste0("SELECT * FROM ",cdm_database_schema,".drug_era")))
drug_exposure_db <- tbl(db, sql(paste0("SELECT * FROM ",cdm_database_schema,".drug_exposure")))
concept_db <- tbl(db, sql(paste0("SELECT * FROM ",vocabulary_database_schema,".concept")))
concept_ancestor_db <- tbl(db, sql(paste0("SELECT * FROM ",vocabulary_database_schema,".concept_ancestor")))
death_db <- tbl(db, sql(paste0("SELECT * FROM ",cdm_database_schema,".death")))
care_site_db <- tbl(db, sql(paste0("SELECT * FROM ",cdm_database_schema,".CARE_SITE")))
location_db <- tbl(db, sql(paste0("SELECT * FROM ",cdm_database_schema,".LOCATION")))


# need to update all tables with lowercase
concept_db <- dplyr::rename_with(concept_db, tolower) %>% dplyr::compute()
person_db <- dplyr::rename_with(person_db, tolower) %>% dplyr::compute()
observation_period_db <- dplyr::rename_with(observation_period_db, tolower) %>% dplyr::compute()
visit_occurrence_db <- dplyr::rename_with(visit_occurrence_db, tolower) %>% dplyr::compute() 
condition_occurrence_db <- dplyr::rename_with(condition_occurrence_db, tolower) %>% dplyr::compute()
measurement_db <- dplyr::rename_with(measurement_db, tolower) %>% dplyr::compute()
observation_db <- dplyr::rename_with(observation_db, tolower) %>% dplyr::compute()
drug_era_db <- dplyr::rename_with(drug_era_db, tolower) %>% dplyr::compute()
drug_exposure_db <- dplyr::rename_with(drug_exposure_db, tolower) %>% dplyr::compute()
concept_ancestor_db <- dplyr::rename_with(concept_ancestor_db, tolower) %>% dplyr::compute()
death_db <- dplyr::rename_with(death_db, tolower) %>% dplyr::compute()
care_site_db <- dplyr::rename_with(care_site_db, tolower) %>% dplyr::compute()
location_db <- dplyr::rename_with(location_db, tolower) %>% dplyr::compute()

# Parameters for filters
age_cutoff <- 50
age_cutoff_max <- 65
conceptID <- 1112807 #asprin
gender <- 8532

#create a table showing how final population is determined from the initial population
Ntot <- person_db %>% tally() %>% pull() #2694 people
exclusion_table <- tibble(concept = "Initial population",N = Ntot)

#pull the info into cohort
cohort <- person_db %>% compute()


# need an age cutoff as in other databases this will be massive if i just want people with aspirin use
cohort <- cohort %>% mutate(age = 2022-year_of_birth) %>% filter(age>=age_cutoff) %>% filter(age<=age_cutoff_max) %>% compute()

#fill up the exclusion table
exclusion_table <- rbind(exclusion_table,c("AGE>50<65",cohort %>% tally() %>% pull()))


tic()
drug_era_cohort <- drug_era_db %>% select(person_id,drug_concept_id,drug_era_start_date) %>% inner_join(cohort %>% select(person_id)) %>% filter(drug_concept_id == conceptID) %>% compute()
toc()

# this extracts the first entry of aspirin use
cohort <- cohort %>% inner_join(drug_era_cohort) %>% group_by(person_id) %>% filter(row_number()==1) %>% compute()

#collect the data
cohort_collected <- cohort %>% collect()

# complete the exclusion data
exclusion_table <- rbind(exclusion_table,c("taking aspirin", cohort_collected %>% nrow ) )

```

## Creating a pretty pyramid plot
```{r pretty_plots,  message=FALSE, warning=FALSE,echo=FALSE}

#pretty pyramid plot
cohort_collected %>% 
  ggplot(.,aes(x=age,fill=gender_source_value)) + 
  geom_bar(data=subset(cohort_collected,gender_source_value=="F"), colour = "black") + 
  geom_bar(data=subset(cohort_collected,gender_source_value=="M"),
           colour = "black",aes(y=..count..*(-1))) + 
  scale_y_continuous(breaks=seq(-50,50,10),labels=abs(seq(-50,50,10))) + 
  scale_x_continuous(expand = c(0,0), breaks=seq(age_cutoff,age_cutoff_max,1),
  labels=abs(seq(age_cutoff,age_cutoff_max,1))) +
  coord_flip() +
  scale_fill_manual("Gender", values = c("F" = "pink", "M" = "cornflowerblue")) +
  theme(panel.background = element_rect(fill = "white", colour = "white"),
        axis.line = element_line(size = 0.5, linetype = "solid", colour = "black"),
        axis.text.y = element_text(size= 7.5 )) +
  xlab("Age") + 
  ylab("Person Count") %>%
labs(title = "Figure 1: Distribution of age for aspirin users over 50 split by gender") +
  ylab("Person Count") #have to rerun this again due to addition of title


ggsave("Figure1_age_distribution.pdf")
```


## Creating table 1 descriptives
```{r table1,  message=FALSE, warning=FALSE,echo=FALSE}

mytable1 <- table1(~  + age  + factor(ethnicity_source_value) + factor(race_source_value), data= cohort_collected)

write.table (mytable1 , "my_table_1_file.csv", col.names = T, row.names=F, append= F, sep=',')

mytable1

```


```{r sessioninfor}

# print out the session information
sessionInfo()

dbDisconnect(db)

```
