---
title: "Style vignedd"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{my-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  warning = FALSE, 
  message = FALSE 
)
```

```{r setup}
library(style.function)
```

```{r}
library(ggalluvial)
library(ggplot2)

df <- as.data.frame(Titanic)

gg_standard <- ggplot(data = df,
                 aes(y = Freq,
                     axis2= Survived,
                     axis1=Class
                 )) +
  geom_alluvium(aes(
    fill = Class)) +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  scale_x_continuous(breaks = 1:2, labels = c("Class", "Survival")) +
  scale_fill_manual(values = c("#033270" , 
                               "#4091C9",
                               "#F29479",
                               "#EF3C2D", 
                               "#A20214")) +
  ylab("Frequency")+
  ggtitle("Titanic survival, by class")


```

# Default plot
```{r, fig.width=6}
gg_standard
 
```

# Modified plot
```{r, fig.width=6}
gg <- gg_standard + style()
gg 
```

